### ISSUE TITLE
No output AT ALL

### ISSUE THREAD

**Issue by iNoSec** [s0md3v/goop#10]
https://github.com/s0md3v/goop/issues/9 like i said i have nothing, no output AT ALL even if i try with your example... the script search because it doesnt close on the same timelapse if i use 1 or 10 (for the results)

**Comment by s0md3v** [comment]
How did you get your facebook cookie?

**Comment by iNoSec** [comment]
I copy/paste all of them, with burp to cli.py. thanks

**Comment by s0md3v** [comment]
@iNoSec I just discovered that the issue has been fixed by Google team. Goop no longer works & will be archived now.
