### ISSUE TITLE
Response from Google

### ISSUE THREAD

**Issue by vimalsheoran** [s0md3v/goop#3]
I read the Linkedin post and it mentioned that you had already reported this to Google, have they sent a response yet, if so what did they say and are they going to fix this in some manner? Thanks.

**Comment by s0md3v** [comment]
1. Facebook scraper allows fetching arbitrary webpages.
2. Google has whitelisted Facebook scraper and doesn't block it's requests.

None of these things is a problem individually but when used together they become problem.
There's nothing to be fixed at either end. I believe it will not be patched.
