### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by iNoSec** [s0md3v/goop#9]
hi,
Thanks for your work, love your github!!!
I add all my facebook cookies but i have no output, tool work i can see it search fast if i ask for 1 output and more slowly if 20 is ask but finally i have no output on my terminal. i dont understand what is the problem here. Thanks in advance

**Comment by s0md3v** [comment]
If you are not getting any output after a few pages, that means there are no more search result pages.

**Comment by iNoSec** [comment]
I search like your example with your name and i have no output AT ALL. If i try with 1 it go fast with no output etc like i said in the first comment
